M48
; DRILL file {KiCad 8.0.1} date 2024-08-03T12:45:28+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-03T12:45:28+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.360
%
G90
G05
T1
X120.425Y-102.11
X120.425Y-107.89
T2
X134.0Y-50.0
X146.0Y-50.0
X154.0Y-50.0
X166.0Y-50.0
M30
